### ISSUE TITLE
Release 1.11.x with Casbah 3.1.1 support (but not Scala 2.12)

### ISSUE THREAD

**Issue by noahlz** [salat/salat#183]
https://groups.google.com/forum/#!topic/scala-salat/SDpFvIUMg_0

> Just seen Scala 2.12 is out. Is salat/casbah complex to update to this new version?

**Comment by Mobyman** [comment]
+1

**Comment by scf37** [comment]
Upgrading to 2.12 requires upgrading casbah -> upgrading mongodb driver -> compliation failure here:
``` 
 private def defaultWriteResultErrorCheck(wr: WriteResult) = wr.getError != null || {
    val lastError = wr.getCachedLastError
    lastError != null && !lastError.ok()
  }
```

`WriteResult` no longer has methods `getError` and `getCachedLastError`

All dependencies seems to be already 2.12-ready.

**Comment by noahlz** [comment]
First of all - thank you for looking into this!  Do you happen to have a pull request with the proposed version change?  I'll take it from there.

Regarding the methods getError and getCachedLastError - I kept those around while upgrading to Mongo 3.0, for backwards compatibility purposes.   If we are leaving older versions of Casbah, Mongo Driver and Mongo Server behind, in a non-backwards compatible manner, I'm inclined to make this upgrade part of a new `1.11.x` branch.

Regarding timeline to get this out, I won't be able to set aside time to work on salat until about mid-Feb (a few weeks from now). If anybody out there reading this urgently needs Scala 2.12 support in Salat, please comment and I'll see about re-shuffling things.

**Comment by noahlz** [comment]
#188 bumps casbah to 3.1.1 which also would delete the unsupported functions. I think both of those will be combined into a 1.11.x branch that is Scala 2.11/2.12 and Mongo 3.1.x only

**Comment by noahlz** [comment]
So it turns out this is not as simple as just bump the version to 2.12 and be on your way.

Specs2 needs to be upgraded to 2.4.17, which has no 2.10 build. 

Further, we use TravisCI to validate pull requests.  The change I pushed to add 2.12 to the TravisCI builds failed.  So it seems the `master`, `1.9.x-branch` and `1.10.x-branch` branches will also need to be upgraded to Specs2 2.4.17 in order for the TravisCI builds to succeed.

salat/salat#190

https://travis-ci.org/salat/salat/

One other blocker: I upgraded Specs2 to 2.4.17, there was a compilation error in a Json spec that I could not figure out right away, so I opened an issue with Specs2 here: 

etorreborre/specs2#553

Any help or feedback / ideas on how to proceed would be appreciated.  Especially anybody with experience supporting TravisCI builds who can advise how to set up the builds such that they build branches independently.

**Comment by noahlz** [comment]
Also 

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalaz.stream#scalaz-stream_2.11;0.5a: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

I need some help on this. Alternatively, we are going to have to take the "legacy" versions of salat off travis and only have this new branch have continuous integration.  

I know what goes into solving this (finding the right combination of versions with binary comparability, and setting up the travis build + sbt configs appropriately) - however, I've exceeded my time budget on this for today. If someone can take over and make some headway on this, that would be much appreciated.

**Comment by pferrel** [comment]
I don't need scala 2.12, just 2.11. But I do need Casbah 3.1.1. 

Does this mean the Specs2 problem goes away? Is there a PR or possible PR for Casbah 3.1.1 in scala 2.11 or one that would work with 2.11?

**Comment by noahlz** [comment]
Ok, let's walk back the whole 2.12.x thing and focus on 2.11 + 3.1.1

I can probably get this on the weekend (3/3 - 3/4) but if someone can open a branch against `1.11.x-branch` that will speed things along.

Sorry for the delay due to the side trip into 2.12 land. Thought I could get two birds with one stone - guess not.

**Comment by noahlz** [comment]
So to clarify the original point of this Issue - we will NOT be supporting Scala 2.12 in the immediate future.  

If someone out there actually needs 2.12, like NEEDS it (you have an imperative to upgrade to 2.12 and Salat is holding you back) please comment.

**Comment by pferrel** [comment]
@noahlz not sure what you mean about opening a branch. I'll fork salat and will definitely help test and/or work on it. I'm quite keen to use Salat for some new work that we are coding right now. I'm a committer to Apache Mahout and Apache PredictionIO, both Scala projects.

I'll add you as a collaborator to this fork: https://github.com/pferrel/salat if that helps.

**Comment by noahlz** [comment]
Apologies, I meant "open a pull request."

**Comment by noahlz** [comment]
@pferrel  Regarding what I meant by "open a ~~branch~~ pull request" please see the `CONTRIBUTING.md` document.

edit: this one https://github.com/salat/salat/blob/1.11.x-branch/CONTRIBUTING.md

`1.11.x-branch` will be the home of casbah 3.1.1+ support

**Comment by pferrel** [comment]
@noahlz is the PR here: https://github.com/salat/salat/pull/191 ok for  start. 

`sbt test:test` has no errors with scala 2.11 and casbah 3.x on my machine.

**Comment by noahlz** [comment]
Ok, I've published a `1.11.0-SNAPSHOT` for both scala 2.11 and 2.10 to the repo.  Note that you need to have the resolver for the Sonatype OSS snapshot repo in your build file to get the snapshot, as per this project:

https://github.com/noahlz/salat-examples/blob/1.11.x-test/build.sbt

Please let me know if this works for Casbah 3.1.1 - if so, will do the official stable release.

**Comment by zfy0701** [comment]
I'm using 1.11.0-SNAPSHOT for a month and it works great for us, would love to see a stable release

**Comment by noahlz** [comment]
Great, I was waiting for feedback like this (aside from also being tied up). Will release this week.

**Comment by noahlz** [comment]
I've completed the release and published signed jars for Scala 2.10 and 2.11 to the Sonatype OSS repo. It should propagate to Central in a few hours. I'm also changing the "default" branch for this project to 1.11.x-branch, as I figure that's where folks will want to direct their PRs going forward.

Please comment if the artifacts do not appear in central - otherwise, I'm closing this ticket.

Sincere thanks to everyone who helped with this release!

**Comment by noahlz** [comment]
Artifacts are now in Maven central. Please comment if you have any problems.
